version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influx
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    env_file:
      - ./influxdb/.env
    networks:
      se4iot:
        ipv4_address: 172.20.0.101
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    ports:
      - 1882:1883
      - 9002:9001
    volumes:
      - ./mosquitto:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log:/mosquitto/log
    networks:
      se4iot:
        ipv4_address: 172.20.0.102
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      se4iot:
        ipv4_address: 172.20.0.103
  sensors:
    build: ./sensors
    container_name: sensors
    hostname: sensors
    restart: always
    env_file:
      - ./mosquitto/.env
    depends_on:
      - mosquitto
      - central-control-system
      - grafana
    networks:
      se4iot:
        ipv4_address: 172.20.0.104
  actuators:
    build: ./actuators
    container_name: actuators
    hostname: actuators
    restart: always
    env_file:
      - ./mosquitto/.env
    depends_on:
      - central-control-system
      - mosquitto
      - grafana
    networks:
      se4iot:
        ipv4_address: 172.20.0.105
  server:
    build: ./backend
    container_name: server
    hostname: server
    restart: "no"
    env_file:
      - ./mosquitto/.env
      - ./backend/.env
      - ./mongodb/.env
      - ./grafana/.env
    ports:
      - 3002:3002
    depends_on:
      - mosquitto
      - mongodb
      - grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:3002/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      se4iot:
        ipv4_address: 172.20.0.106
  central-control-system:
    build: ./central-control-system
    container_name: central-control-system
    hostname: central-control-system
    restart: always
    env_file:
      - ./backend/.env
      - ./mosquitto/.env
    depends_on:
      server:
          condition: service_healthy
      mosquitto:
          condition: service_started
    networks:
      se4iot:
        ipv4_address: 172.20.0.107
  node-red:
    build: ./node-red
    container_name: node-red
    hostname: nodered
    restart: always
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data
    env_file:
      - ./influxdb/.env
      - ./mosquitto/.env
      - ./backend/.env
      - ./grafana/.env
    depends_on:
      influxdb:
        condition: service_started
      mosquitto:
        condition: service_started
      server:
        condition: service_healthy
    networks:
      se4iot:
        ipv4_address: 172.20.0.108
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/.env
      - ./influxdb/.env
      - ./postgresql/.env
    depends_on:
      influxdb:
        condition: service_started
      postgresql:
        condition: service_healthy
    networks:
      se4iot:
        ipv4_address: 172.20.0.109
  postgresql:
    image: postgres:latest
    container_name: postgresql
    hostname: postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./postgresql/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_GRAFANA_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      se4iot:
        ipv4_address: 172.20.0.110
networks:
  se4iot:
    ipam:
      config:
        - subnet: 172.20.0.0/16
