
apiVersion: 1

datasources:
  - name: se4iot
    type: influxdb
    url: http://${INFLUXDB_HOST}:${INFLUXDB_PORT}
    uid: ${INFLUXDB_DATASOURCE_UID}
    access: proxy
    isDefault: true
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}