import { ACTUATOR_TYPES } from './actuatorTypes.js'
import { SENSOR_TYPES } from './sensorType.js'

export const ACTUATOR_TO_SENSOR = {
  [ACTUATOR_TYPES.LIGHTBULB]: SENSOR_TYPES.LIGHT,
  [ACTUATOR_TYPES.AIR_CONDITIONER]: SENSOR_TYPES.TEMPERATURE
}

export const SENSOR_TO_ACTUATOR = {
  [SENSOR_TYPES.LIGHT]: ACTUATOR_TYPES.LIGHTBULB,
  [SENSOR_TYPES.TEMPERATURE]: ACTUATOR_TYPES.AIR_CONDITIONER,
  [SENSOR_TYPES.MOTION]: ACTUATOR_TYPES.LIGHTBULB
}
